context.modules = [
  {
    name = libpipewire-module-loopback
    args = {
      node.description = "Line-In Loopback"
      capture.props = {
        audio.position = [ FL FR ]
        target.object = "YOUR_DEVICE_ALSA_INPUT_NAME"
        stream.dont-remix = true
      }
      playback.props = {
        audio.position = [ FL FR ]
        target.object = "YOUR_DEVICE_ALSA_OUTPUT_NAME"
        stream.dont-remix = true
      }
    }
  }
]
