monitor.alsa.rules = [
  {
    matches = [
      { device.name = "YOUR_DEVICE_CARD_NAME" }
    ]
    actions = {
      update-props = {
        device.profile = "output:analog-stereo+input:analog-stereo"
      }
    }
  }
]
