context.modules = [
  {
    name = libpipewire-module-loopback
    args = {
      node.description = "Switch Line-In Loopback"
      capture.props = {
        audio.position = [ FL FR ]
        target.object = "alsa_input.usb-Creative_Technology_Ltd_Sound_Blaster_X3_FACA0D7DF9F2D4AF-03.analog-stereo"
        stream.dont-remix = true
      }
      playback.props = {
        audio.position = [ FL FR ]
        target.object = "alsa_output.usb-Creative_Technology_Ltd_Sound_Blaster_X3_FACA0D7DF9F2D4AF-03.analog-stereo.4"
        stream.dont-remix = true
      }
    }
  }
]
