monitor.alsa.rules = [
  {
    matches = [
      { device.name = "alsa_card.usb-Creative_Technology_Ltd_Sound_Blaster_X3_FACA0D7DF9F2D4AF-03" }
    ]
    actions = {
      update-props = {
        device.profile = "output:analog-stereo+input:analog-stereo"
      }
    }
  }
]
